import type { Metadata } from 'next';

import { TRPCReactProvider } from '~/trpc/react';

import '@kaos/ui/globals.css';

import type { ReactNode } from 'react';
import { Navbar } from '~/components';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang='en'>
      <body>
        <TRPCReactProvider>
          <Navbar />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
