services:
    kaos-agent:
        command: ["pnpm", "start"]
        image: envoyvc/kaos-agent:latest
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - MISTRAL_API_KEY
            - MISTRAL_MODEL
            - SERVER_PORT
            - POSTGRES_URL
        ports:
            - "3000:3000"
        restart: always