[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "../" }]

eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143
